version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: ./example/Dockerfile.integration-tests
    volumes:
      - "./example/integration-tests:/integration-tests"
      - "./example/screenshots:/screenshots"
    command: "wait-for-it.sh web:80 -- mocha --recursive /integration-tests"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./git-contributions/Dockerfile
    expose:
      - "80"
